name: Build RAL APK (Debug & Safe)

on:
  workflow_dispatch:
    inputs:
      build_debug:
        description: 'Build Debug'
        type: boolean
        default: true
      build_safe:
        description: 'Build Safe Release'
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ✅ Java 17 (quan trọng)
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - uses: android-actions/setup-android@v3

      - run: chmod +x ./gradlew

      # ================= DEBUG =================
      - name: Build Debug
        if: github.event.inputs.build_debug == 'true'
        run: ./gradlew assembleDebug -x lint -x test --no-daemon --parallel

      - name: Upload Debug
        if: github.event.inputs.build_debug == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: RAL-Debug
          path: app/build/outputs/apk/debug/*.apk

      # ================= SAFE RELEASE =================
      - name: Build Release
        if: github.event.inputs.build_safe == 'true'
        run: ./gradlew assembleRelease -x lint -x test --no-daemon --parallel

      - name: Upload Release
        if: github.event.inputs.build_safe == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: RAL-Release
          path: app/build/outputs/apk/release/*.apk
